name: Java

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Build
        run: mvn --batch-mode --no-transfer-progress clean package

      - name: Test
        run: mvn --batch-mode --no-transfer-progress test || true

      - name: Test report
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: '**/surefire-reports/TEST-*.xml'
          fail_on_failure: false
